GetCustomer API Star Wars
daniccarvalho01/microservices-study pull request #11
Opened 2022-05-12 23:25 UTC by daniccarvalho01

2022-05-13 01:32 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/OrderApplication.java
> +@EnableFeignClients
🤭

2022-05-13 01:33 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/client/CustomerAPI.java
> +@FeignClient(value = "customerAPI",  url = "${client.order.url}")
Seria bom alterar a configuração `${client.order.url}` para algo de customer para não se confundir no futuro pensando que é uma configuração que vai buscar algo de ordem.

2022-05-13 01:34 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/client/CustomerAPI.java
> +    @GetMapping(value= "people/{clientId}")
Faltou mudar aqui e no parâmetro para `customerId`

2022-05-13 01:35 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/domain/mapper/OrderMapper.java
> +        order.setCustomerId(request.getCustomerId());
Muito bom!

2022-05-13 01:38 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/CustomerService.java
> +public class CustomerService {
Gostei que você criou esse Service

2022-05-13 01:39 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +    StoreService storeService;
faltou o `private`

2022-05-13 01:39 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +    CustomerService customerService;
faltou o `private`

2022-05-13 01:41 UTC, guilhermelodi commented on order/src/main/resources/SQL/DDL.sql
> +    client_id int not null,
você alterou para customer_id por solicitação de uma pessoa muito legal 😎

2022-05-13 01:42 UTC, guilhermelodi commented on order/src/main/resources/application.properties
> +client.order.url=https://swapi.dev/api/
Mudar para algo de customer

2022-05-13 01:42 UTC, guilhermelodi requested changes
Muito bem!! Gostei tanto do refactor quanto da implementação. Assim que você finalizar, me avise que eu reviso novamente.

2022-05-16 00:33 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/OrderApplication.java
> +@EnableFeignClients
:-)

2022-05-16 00:34 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/client/CustomerAPI.java
> +    @GetMapping(value= "people/{clientId}")
Concordo. Feito

2022-05-16 00:34 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/domain/mapper/OrderMapper.java
> +        order.setCustomerId(request.getCustomerId());
:)

2022-05-16 00:35 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/service/CustomerService.java
> +public class CustomerService {
Cada um fica com seu serviço né?

2022-05-16 00:36 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +    StoreService storeService;
Ok. Feito

2022-05-16 00:36 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +    CustomerService customerService;
ok

2022-05-16 00:36 UTC, daniccarvalho01 commented on order/src/main/resources/SQL/DDL.sql
> +    client_id int not null,
Um chatão!!

2022-05-16 00:37 UTC, daniccarvalho01 commented on order/src/main/resources/application.properties
> +client.order.url=https://swapi.dev/api/
Concordo. Feito

2022-05-16 01:18 UTC, guilhermelodi commented on order/src/main/resources/SQL/DDL.sql
> +    client_id int not null,
😂 😂 😂 😂 😂 
Dani, faltou mudar a linha 7 para customer_id para manter o histórico.

2022-05-16 01:27 UTC, guilhermelodi approved these changes
Falta só ajustar o DDL, mas já vou deixar aprovado.

Bom trabalho Dani. 🚀

2022-05-17 22:11 UTC, merged