Dev 6
daniccarvalho01/microservices-study pull request #6
Opened 2022-01-30 06:54 UTC by daniccarvalho01

2022-01-30 13:08 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +    private OrderItemRepository itemRepository;
Não encontrei utilização desse `repository` na classe

2022-01-30 13:13 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +        order.setStore(request.getStore());
Não precisa, mas talvez uma refatoração legal, seria:
Agora que você tem um `OrderMapper` que converte para `response`, talvez criar mais um método que converte a `request` para `entity`.

2022-01-30 13:15 UTC, guilhermelodi reviewed
Muito muito bom mesmo.
Era exatamente dessa forma que eu esperava o retorno da ordem.
Veja os comentários que fiz e se fizer sentido, assim que finalizar, me avise que eu aprovo.
😍💻

2022-01-30 14:09 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +    private OrderItemRepository itemRepository;
Realmente não tinha uso. Deletado.

2022-01-30 14:23 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +        order.setStore(request.getStore());
Concordo! Implementado

2022-01-30 21:30 UTC, guilhermelodi requested changes
Só remover os beans, testar e subir que eu aprovo

2022-01-30 21:30 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/domain/mapper/OrderMapper.java
> +    @Bean
Não precisa do `@Bean` no método

2022-01-30 21:30 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/domain/mapper/OrderMapper.java
> +    @Bean
Aqui também não.

2022-01-30 21:30 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +        Order order = OrderMapper.toEntity(request);
Muito bem!

2022-01-31 00:11 UTC, guilhermelodi approved these changes

2022-01-31 00:17 UTC, merged