Dev 10
daniccarvalho01/microservices-study pull request #9
Opened 2022-03-07 23:00 UTC by daniccarvalho01

2022-03-08 01:55 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/domain/entity/Order.java
> +import com.microservicestudy.order.domain.response.StoreResponse;
Adicionou o import, mas não está usando

2022-03-08 01:58 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +import com.microservicestudy.order.domain.response.OrderResponse;
Não estamos usando esse import.

2022-03-08 01:59 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +//        OrderResponse orderResponse = new OrderResponse();
Como é um código ultrapassado, podemos apagar.

2022-03-08 02:00 UTC, guilhermelodi commented on store/src/main/java/com/microservicesstudy/store/domain/response/StoreResponse.java
> -
Muito obrigado :hand_over_mouth:

2022-03-08 02:01 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/resource/OrderResource.java
> +        StoreResponse storeResponse;
O código de obtenção do StoreReponse está duplicado, será que não conseguimos movê-lo para o Service como um método e chamá-lo quando precisarmos?

2022-03-08 02:02 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +import com.microservicestudy.order.domain.response.OrderResponse;
Import não utilizado

2022-03-08 02:03 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/domain/mapper/OrderMapper.java
> +        for (OrderItem item : order.getItems()) {
Hmm... Agora que já estamos mais acostumados com o projeto, será que conseguimos utilizar alguma feature do Java8 para melhorar esse for each?

2022-03-08 02:05 UTC, guilhermelodi requested changes
Quando finalizar os ajustes dos comentários, me avise. 
Bom trabalho!
Você melhora e melhora! :clap::clap:

2022-03-08 22:19 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/domain/entity/Order.java
> +import com.microservicestudy.order.domain.response.StoreResponse;
Corrigido!

2022-03-08 22:20 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +//        OrderResponse orderResponse = new OrderResponse();
Corrigido!

2022-03-08 22:20 UTC, daniccarvalho01 commented on store/src/main/java/com/microservicesstudy/store/domain/response/StoreResponse.java
> -
😘

2022-03-08 22:39 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/resource/OrderResource.java
> +        StoreResponse storeResponse;
Sim. Faz sentido! Feito

2022-03-08 22:40 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/service/OrderService.java
> +import com.microservicestudy.order.domain.response.OrderResponse;
Corrigido

2022-03-09 14:06 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/resource/OrderResource.java
> +            }
A indentação dessa chave está pra frente

2022-03-09 14:08 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/StoreService.java
> +public class StoreService {
Aqui teremos um problema e acredito que pelo seu BD não estar funcionando, você não chegou a ver. Mas você consegue perceber qual é?

2022-03-09 14:10 UTC, daniccarvalho01 commented on order/src/main/java/com/microservicestudy/order/service/StoreService.java
> +public class StoreService {
Sim. ta faltando o @Service 
é isso?

2022-03-09 18:43 UTC, guilhermelodi commented on order/src/main/java/com/microservicestudy/order/service/StoreService.java
> +public class StoreService {
isso mesmo ;)

2022-04-05 02:26 UTC, guilhermelodi approved these changes

2022-04-05 02:27 UTC, merged